const types = {
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  GET_HEADER_HEIGHT: 'GET_HEADER_HEIGHT',
  FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
  FETCH_EMPLOYEES_STATUS: 'FETCH_EMPLOYEES_STATUS',
  FETCH_EMPLOYEES_FAIL: 'FETCH_EMPLOYEES_FAIL',
};

export default types;
